/**
 * ============================================================================
 *  WARNING — THIS FILE IS SOURCE-CONTROLLED (spiralpalooza git repo)
 *
 *  DO NOT EDIT this file until you have read the "Working on the Apps Script
 *  backends with clasp" section of the repo's README.md. Editing the live
 *  version directly can drift from, or be overwritten by, the git copy.
 * ============================================================================
 *
 * Spiralpalooza Volunteer — Apps Script backend (container-bound to the
 * Volunteers sheet).
 *
 * Endpoints:
 *   doPost  — append a new volunteer signup
 *
 * Sheet headers (row 1, created on first write):
 *   Timestamp | Name | Email | Phone | Volunteer Roles | Availability |
 *   CF Connection | Notes
 */
function doPost(e) {
  try {
    var data = JSON.parse(e.postData.contents);

    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = ss.getSheetByName("Volunteers")
               || ss.insertSheet("Volunteers");

    if (sheet.getLastRow() === 0) {
      sheet.appendRow([
        "Timestamp",
        "Name",
        "Email",
        "Phone",
        "Volunteer Roles",
        "Availability",
        "CF Connection",
        "Notes"
      ]);
      sheet.getRange(1, 1, 1, 8).setFontWeight("bold");
      sheet.setFrozenRows(1);
    }

    sheet.appendRow([
      new Date(),
      data.name         || "",
      data.email        || "",
      data.phone        || "",
      data.roles        || "",
      data.availability || "",
      data.connection   || "",
      data.notes        || ""
    ]);

    return ContentService
      .createTextOutput(JSON.stringify({status:"success"}))
      .setMimeType(ContentService.MimeType.JSON);

  } catch(err) {
    return ContentService
      .createTextOutput(JSON.stringify({status:"error",message:err.toString()}))
      .setMimeType(ContentService.MimeType.JSON);
  }
}
