/**
 * ============================================================================
 *  WARNING — THIS FILE IS SOURCE-CONTROLLED (spiralpalooza git repo)
 *
 *  DO NOT EDIT this file until you have read the "Working on the Apps Script
 *  backends with clasp" section of the repo's README.md. Editing the live
 *  version directly can drift from, or be overwritten by, the git copy.
 * ============================================================================
 *
 * Spiralpalooza Volunteer — Apps Script backend (container-bound to the
 * Volunteers sheet).
 *
 * Endpoints:
 *   doPost  — append a new volunteer signup
 *
 * Sheet headers (row 1, created on first write):
 *   Timestamp | Name | Email | Phone | Volunteer Roles | Availability | Notes
 */
function doPost(e) {
  try {
    var data = JSON.parse(e.postData.contents);

    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = ss.getSheetByName("Volunteers")
               || ss.insertSheet("Volunteers");

    // Column order is defined once here; the header row and each data row are
    // both derived from this map, so they can't drift out of sync.
    var record = {
      "Timestamp":       new Date(),
      "Name":            data.name         || "",
      "Email":           data.email        || "",
      "Phone":           data.phone        || "",
      "Volunteer Roles": data.roles        || "",
      "Availability":    data.availability || "",
      "Notes":           data.notes        || ""
    };
    var headers = Object.keys(record);

    if (sheet.getLastRow() === 0) {
      sheet.appendRow(headers);
      sheet.getRange(1, 1, 1, headers.length).setFontWeight("bold");
      sheet.setFrozenRows(1);
    }

    sheet.appendRow(headers.map(function(h) { return record[h]; }));

    return ContentService
      .createTextOutput(JSON.stringify({status:"success"}))
      .setMimeType(ContentService.MimeType.JSON);

  } catch(err) {
    return ContentService
      .createTextOutput(JSON.stringify({status:"error",message:err.toString()}))
      .setMimeType(ContentService.MimeType.JSON);
  }
}
