/**
 * ============================================================================
 *  WARNING — THIS FILE IS SOURCE-CONTROLLED (spiralpalooza git repo)
 *
 *  DO NOT EDIT this file until you have read the "Working on the Apps Script
 *  backends with clasp" section of the repo's README.md. Editing the live
 *  version directly can drift from, or be overwritten by, the git copy.
 * ============================================================================
 *
 * Spiralpalooza RSVP — Apps Script backend (container-bound to the RSVPs sheet).
 *
 * Endpoints:
 *   doPost  — append a new RSVP, or update an existing one by edit token
 *   doGet   — ?edit=<token> returns one record for the edit form;
 *             otherwise returns the public "Who's Coming" list
 *
 * Sheet headers (row 1, any order — reads/writes are header-keyed):
 *   Timestamp | First Name | Last Name | Email | Phone | Mailing Address |
 *   Years at Children First | Attending | Role / Affiliation | Party Members |
 *   Total in Party | List Permission | Private Notes | Public Notes |
 *   Pizza GF | Pizza Vegan | Pizza GF+Vegan | Edit Token | Last Updated
 *
 * Script Properties (Project Settings -> Script Properties):
 *   MAILER_URL   — /exec URL of the shared mailer microservice
 *   MAIL_SECRET  — shared secret the mailer checks (same value as the mailer)
 */

// ---- Config ----------------------------------------------------------------

var RSVP_SHEET_NAME = 'RSVPs';

// Live site base URL, must end with '/'. Used to build the edit link in emails.
var SITE_URL = 'https://spiralpalooza.org/';

// Canonical header row, in order. ensureHeaders_ uses this to create the sheet or
// to backfill any missing columns (e.g. Edit Token / Last Updated on a sheet from
// before the edit-link feature). The tests also build their sheet from this.
var RSVP_HEADERS = [
  'Timestamp', 'First Name', 'Last Name', 'Email', 'Phone', 'Mailing Address',
  'Years at Children First', 'Attending', 'Role / Affiliation', 'Party Members',
  'Total in Party', 'List Permission', 'Private Notes', 'Public Notes',
  'Pizza GF', 'Pizza Vegan', 'Pizza GF+Vegan', 'Edit Token', 'Last Updated'
];

// ---- Write path (doPost) ---------------------------------------------------

function doPost(e) {
  try {
    var data = JSON.parse(e.postData.contents);

    // Reject incomplete submissions before touching the sheet or sending mail.
    // This is data-integrity validation, NOT access control — the endpoint is public.
    var problem = validateRsvp_(data);
    if (problem) {
      return ContentService
        .createTextOutput(JSON.stringify({ status: "error", message: problem }))
        .setMimeType(ContentService.MimeType.JSON);
    }

    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = ss.getSheetByName(RSVP_SHEET_NAME) || ss.insertSheet(RSVP_SHEET_NAME);
    ensureHeaders_(sheet);

    var saved = saveRsvp_(sheet, data);

    sendEmail_(data, saved.token, saved.isUpdate);

    return ContentService
      .createTextOutput(JSON.stringify({ status: "success" }))
      .setMimeType(ContentService.MimeType.JSON);

  } catch (err) {
    console.error('doPost failed: ' + (err && err.stack ? err.stack : err));
    return ContentService
      .createTextOutput(JSON.stringify({ status: "error", message: err.toString() }))
      .setMimeType(ContentService.MimeType.JSON);
  }
}

// Maps an incoming RSVP payload to sheet columns by header text. Timestamp,
// Edit Token, and Last Updated are managed by doPost / updateRowByToken_.
function rsvpRow_(data) {
  return {
    'First Name':              data.firstName,
    'Last Name':               data.lastName,
    'Email':                   data.email,
    'Phone':                   data.phone,
    'Mailing Address':         data.address,
    'Years at Children First': data.years,
    'Attending':               data.attending || 'Yes',
    'Role / Affiliation':      data.role,
    'Party Members':           data.partyMembers,
    'Total in Party':          data.totalInParty,
    'List Permission':         data.listPermission,
    'Private Notes':           data.notesPrivate,
    'Public Notes':            data.notesPublic,
    'Pizza GF':                data.pizzaGF || 0,
    'Pizza Vegan':             data.pizzaVegan || 0,
    'Pizza GF+Vegan':          data.pizzaGFVegan || 0
  };
}

// Writes the RSVP to the sheet: updates the row matching data.editToken if found,
// otherwise appends a new row with a fresh token. Returns { token, isUpdate }.
// No email/validation here — kept separate from doPost so the write path can be
// tested without going through the email code path.
function saveRsvp_(sheet, data) {
  var values = rsvpRow_(data);

  if (data.editToken) {
    values['Last Updated'] = new Date();
    if (updateRowByToken_(sheet, data.editToken, values)) {
      return { token: data.editToken, isUpdate: true };
    }
  }
  var token = Utilities.getUuid();      // new RSVP, or editToken not found (falls back to new)
  values['Timestamp'] = new Date();
  values['Edit Token'] = token;
  appendByHeader_(sheet, values);
  return { token: token, isUpdate: false };
}

// Validates the genuinely required RSVP fields for data integrity (NOT access
// control — the endpoint is public; this just keeps junk/incomplete rows out).
// Returns an error message string, or '' if the payload is acceptable.
function validateRsvp_(data) {
  if (!data) return 'Missing request body.';
  if (!String(data.firstName || '').trim()) return 'First name is required.';
  if (!String(data.lastName  || '').trim()) return 'Last name is required.';
  var email = String(data.email || '').trim();
  if (!email || email.indexOf('@') === -1)  return 'A valid email is required.';
  if (!String(data.years || '').trim())     return 'Years at Children First is required.';
  return '';
}

// Create the sheet's header row if it's empty, or backfill any missing headers
// (Edit Token / Last Updated may not exist on a sheet from before the edit-link
// feature). Existing columns and their order are left untouched; new headers are
// appended at the end, and existing data rows just get blank cells under them.
function ensureHeaders_(sheet) {
  if (sheet.getLastRow() === 0) {
    sheet.appendRow(RSVP_HEADERS);
    sheet.getRange(1, 1, 1, RSVP_HEADERS.length).setFontWeight('bold');
    sheet.setFrozenRows(1);
    return;
  }
  // getLastColumn() is the widest used column across the whole sheet, so a data
  // row wider than the header row would pad row 1 with trailing blanks. Trim those
  // so missing headers append right after the real ones, not after empty gap columns.
  var rowOne = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0]
    .map(function (h) { return String(h).trim(); });
  var width = rowOne.length;
  while (width > 0 && rowOne[width - 1] === '') width--;
  var headers = rowOne.slice(0, width);
  var missing = RSVP_HEADERS.filter(function (h) { return headers.indexOf(h) === -1; });
  if (missing.length) {
    var start = width + 1;
    sheet.getRange(1, start, 1, missing.length).setValues([missing]).setFontWeight('bold');
  }
}

// Append a row by matching the values object's keys to the sheet's header row.
// Column order in the sheet does not have to match code order: a header with no
// matching key is left blank, and a key with no matching header is ignored.
function appendByHeader_(sheet, values) {
  var headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
  var row = headers.map(function (h) {
    var key = String(h).trim();
    return Object.prototype.hasOwnProperty.call(values, key) ? values[key] : '';
  });
  sheet.appendRow(row);
}

// Finds the row whose 'Edit Token' matches and overwrites it. Columns not present
// in `values` (Timestamp, Edit Token) keep their existing cell. Returns false if
// no row matches, so doPost can fall back to appending a new row.
function updateRowByToken_(sheet, token, values) {
  var grid = sheet.getDataRange().getValues();
  var headers = grid[0];
  var tokenCol = headers.indexOf('Edit Token');
  if (tokenCol === -1) return false;

  for (var i = 1; i < grid.length; i++) {
    if (String(grid[i][tokenCol]) === String(token)) {
      var row = headers.map(function (h, c) {
        var key = String(h).trim();
        return Object.prototype.hasOwnProperty.call(values, key) ? values[key] : grid[i][c];
      });
      sheet.getRange(i + 1, 1, 1, row.length).setValues([row]);
      return true;
    }
  }
  return false;
}

// ---- Read path (doGet) -----------------------------------------------------

function doGet(e) {
  if (e && e.parameter && e.parameter.edit) {
    return getRsvpForEdit_(e.parameter.edit);
  }

  try {
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(RSVP_SHEET_NAME);

    if (!sheet || sheet.getLastRow() <= 1) {
      return ContentService
        .createTextOutput(JSON.stringify({ status: "success", rsvps: [], grouped: [] }))
        .setMimeType(ContentService.MimeType.JSON);
    }

    var rows = sheet.getDataRange().getValues();
    var headers = rows.shift();
    var col = {};
    headers.forEach(function (h, i) { col[String(h).trim()] = i; });

    var rsvps   = [];  // flat: host + each party member as its own entry
    var grouped = [];  // nested: one entry per host, party members in a "party" array

    rows.forEach(function (r) {
      // Skip anyone who said they can't attend.
      if (String(r[col['Attending']]).trim().toLowerCase() === 'no') return;
      // Only list people who gave permission.
      if (String(r[col['List Permission']]).trim().toLowerCase() !== 'yes') return;

      var hostName = (String(r[col['First Name']] || '').trim() + ' ' +
                      String(r[col['Last Name']]  || '').trim()).trim();
      if (!hostName) return;

      var years = (r[col['Years at Children First']] || '').toString().trim();
      var note  = (r[col['Public Notes']] || '').toString().trim();

      // Party members are stored as "Name (rel) [email]"; strip both the bracketed
      // email and the parenthetical relationship so the public list shows names only.
      var party = String(r[col['Party Members']] || '')
        .split(/\s*\|\s*/)
        .map(function (m) {
          return m.replace(/\s*\[[^\]]*\]\s*/g, '').replace(/\s*\([^)]*\)\s*/g, '').trim();
        })
        .filter(function (m) { return m; });

      rsvps.push({ name: hostName, years: years, note: note });
      party.forEach(function (m) { rsvps.push({ name: m, years: years }); });

      grouped.push({ name: hostName, years: years, note: note, party: party });
    });

    rsvps.sort(function (a, b) { return a.name.localeCompare(b.name); });
    grouped.sort(function (a, b) { return a.name.localeCompare(b.name); });

    return ContentService
      .createTextOutput(JSON.stringify({ status: "success", rsvps: rsvps, grouped: grouped }))
      .setMimeType(ContentService.MimeType.JSON);

  } catch (err) {
    return ContentService
      .createTextOutput(JSON.stringify({ status: "error", message: err.toString() }))
      .setMimeType(ContentService.MimeType.JSON);
  }
}

// Returns one record by edit token, shaped for the edit form: {found, record}.
function getRsvpForEdit_(token) {
  try {
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(RSVP_SHEET_NAME);
    var grid = sheet.getDataRange().getValues();
    var headers = grid[0];
    var col = {};
    headers.forEach(function (h, i) { col[String(h).trim()] = i; });
    var tokenCol = col['Edit Token'];

    var result = { found: false };
    if (tokenCol != null) {
      for (var i = 1; i < grid.length; i++) {
        if (String(grid[i][tokenCol]) === String(token)) {
          var r = grid[i];
          var get = function (name) { return col[name] != null ? r[col[name]] : ''; };
          result = {
            found: true,
            record: {
              firstName:      get('First Name'),
              lastName:       get('Last Name'),
              email:          get('Email'),
              phone:          get('Phone'),
              address:        get('Mailing Address'),
              years:          get('Years at Children First'),
              attending:      get('Attending') || 'Yes',
              role:           get('Role / Affiliation'),
              party:          parseParty_(get('Party Members')),
              pizzaGF:        get('Pizza GF') || 0,
              pizzaVegan:     get('Pizza Vegan') || 0,
              pizzaGFVegan:   get('Pizza GF+Vegan') || 0,
              notesPrivate:   get('Private Notes'),
              notesPublic:    get('Public Notes'),
              listPermission: get('List Permission') || 'No'
            }
          };
          break;
        }
      }
    }
    return ContentService
      .createTextOutput(JSON.stringify(result))
      .setMimeType(ContentService.MimeType.JSON);

  } catch (err) {
    console.error('getRsvpForEdit_ failed: ' + err);
    return ContentService
      .createTextOutput(JSON.stringify({ found: false, error: err.toString() }))
      .setMimeType(ContentService.MimeType.JSON);
  }
}

// "Name (rel) [email] | Name2 (rel2)" -> [{name, rel, email}, ...]
// Assumes names/relationships don't themselves contain "|", "(", ")", "[", or "]"
// (the frontend's serialization format); such characters will misparse. Acceptable
// for this audience — revisit (e.g. store JSON) if that constraint ever bites.
function parseParty_(s) {
  return String(s || '').split(/\s*\|\s*/).filter(function (m) { return m.trim(); }).map(function (m) {
    var email = '', rel = '';
    var em = m.match(/\[([^\]]*)\]/); if (em) { email = em[1]; m = m.replace(em[0], ''); }
    var rm = m.match(/\(([^)]*)\)/);  if (rm) { rel   = rm[1]; m = m.replace(rm[0], ''); }
    return { name: m.trim(), rel: rel.trim(), email: email.trim() };
  });
}

// ---- Email -----------------------------------------------------------------

// Build and send the RSVP confirmation. Best-effort: sendConfirmation_ swallows
// failures, and we bail early if there's no usable email address.
function sendEmail_(data, token, isUpdate) {
  if (!data.email || data.email.indexOf('@') === -1) return;
  var base = pickSiteBase_(data.siteUrl);
  var sep = base.indexOf('?') === -1 ? '?' : '&';
  var editUrl = token ? (base + sep + 'edit=' + token + '&type=rsvp') : '';
  sendConfirmation_(data.email, 'Your Spiralpalooza RSVP', genEmailHTML_(data, editUrl, isUpdate));
}

// Builds the edit-link base from the URL the form was served from (data.siteUrl),
// so links work across local/preview/production without code changes. The caller's
// URL is only trusted if its host is on the allowlist — otherwise we fall back to
// the configured SITE_URL, to avoid becoming a phishing/open-redirect vector (the
// link lands in an email, so an attacker-controlled URL could not be allowed through).
function pickSiteBase_(clientUrl) {
  if (clientUrl && /^https?:\/\//i.test(clientUrl)) {
    // Match on the URL's HOST, not a substring — a substring check would also let
    // "https://evil.com/?x=localhost" or "https://localhost.attacker.com/" through.
    var m = clientUrl.match(/^https?:\/\/([^\/?#]+)/i);
    var host = m ? m[1].split(':')[0].toLowerCase() : '';
    if (host === 'localhost' || host === '127.0.0.1' ||
        host === 'spiralpalooza.org' || host.endsWith('.spiralpalooza.org') ||
        host === 'spiralpalooza.pages.dev' || host.endsWith('.spiralpalooza.pages.dev')) {
      return clientUrl;
    }
  }
  return SITE_URL;
}

// Generate the email HTML. Factored out to make this testable without sending email.
function genEmailHTML_(data, editUrl, isUpdate) {
  var heading = isUpdate ? 'Your RSVP has been updated' : 'Your RSVP is in. Thank you!';
  var editLine = editUrl
    ? '<p style="color:#7A4010;font-size:13px">Need to change anything? Use your personal link to update your RSVP:<br><a href="' + editUrl + '">' + editUrl + '</a></p>'
    : '';

  // Regret
  if (data.attending === 'No') {
    return [
      '<div style="font-family:Arial,sans-serif;color:#3D1C00;line-height:1.6">',
        '<h2 style="color:#7B3A0E">' + heading + '</h2>',
        '<p>Hi ' + esc_(data.firstName) + ',</p>',
        '<p>Thanks for letting us know you can\'t make it to ' +
          'Spiralpalooza on Saturday, October 3, 2026. We\'ll miss you!</p>',
        (data.notesPublic ? '<p><strong>Your message:</strong> ' + esc_(data.notesPublic) + '</p>' : ''),
        '<p>If your plans change, you can update your RSVP using the link below.</p>',
        editLine,
      '</div>'
    ].join('');
  }

  // Attending
  var members = (data.partyMembers || '').split(/\s*\|\s*/).filter(function (m) { return m.trim(); });
  var partyHtml = members.length
    ? '<ul>' + members.map(function (m) { return '<li>' + esc_(m) + '</li>'; }).join('') + '</ul>'
    : '<p>(just you, for now)</p>';

  // Special-order pizza counts — only show the ones that are non-zero.
  var pizzaParts = [];
  if (data.pizzaGF)      pizzaParts.push(esc_(data.pizzaGF) + ' gluten-free');
  if (data.pizzaVegan)   pizzaParts.push(esc_(data.pizzaVegan) + ' vegan');
  if (data.pizzaGFVegan) pizzaParts.push(esc_(data.pizzaGFVegan) + ' gluten-free + vegan');
  var pizzaHtml = pizzaParts.length
    ? '<p><strong>Special-order pizza:</strong> ' + pizzaParts.join(', ') + '</p>'
    : '';

  return [
    '<div style="font-family:Arial,sans-serif;color:#3D1C00;line-height:1.6">',
      '<h2 style="color:#7B3A0E">' + heading + '</h2>',
      '<p>Hi ' + esc_(data.firstName) + ',</p>',
      '<p>We can\'t wait to see you at Spiralpalooza on ' +
        '<strong>Saturday, October 3, 2026</strong> at the Children First Playground, ' +
        '1211 Carroll St, Durham, NC.</p>',
      '<p><strong>Here\'s what you told us:</strong></p>',
      '<ul>',
        '<li><strong>Name:</strong> ' + esc_(data.firstName) + ' ' + esc_(data.lastName) + '</li>',
        '<li><strong>Years with Children First:</strong> ' + esc_(data.years) + '</li>',
        (data.role ? '<li><strong>CF Affiliation:</strong> ' + esc_(data.role) + '</li>' : ''),
      '</ul>',
      '<p><strong>Your party:</strong></p>',
      partyHtml,
      pizzaHtml,
      (data.notesPublic ? '<p><strong>Your public note:</strong> ' + esc_(data.notesPublic) + '</p>' : ''),
      (data.notesPrivate ? '<p><strong>Your private note (only the organizers see this):</strong> ' + esc_(data.notesPrivate) + '</p>' : ''),
      editLine,
    '</div>'
  ].join('');
}

// Best-effort confirmation send. Calls the mailer microservice server-to-server
// so the email goes out from childrenfirstmail, not from this script's owner.
// Never throws — a mail hiccup must not fail the RSVP/order/volunteer write.
// A copy of this goes in each script.
function sendConfirmation_(to, subject, htmlBody) {
  try {
    var props = PropertiesService.getScriptProperties();
    var url = props.getProperty('MAILER_URL');
    var secret = props.getProperty('MAIL_SECRET');
    if (!url || !secret || !to) return;

    UrlFetchApp.fetch(url, {
      method: 'post',
      contentType: 'application/json',
      muteHttpExceptions: true,
      payload: JSON.stringify({ secret: secret, to: to, subject: subject, htmlBody: htmlBody })
    });
  } catch (err) {
    // swallow — confirmation email is non-critical
  }
}

// Escape user-supplied text before dropping it into HTML.
function esc_(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// Quick and dirty test function, just intended to be called by hand.
function testSendEmail() {
  var data = {
    firstName: 'Chloe',
    lastName: 'Palenchar',
    email: 'chloe.palenchar@gmail.com',   // <-- put your address here so you can eyeball it
    phone: '919-555-0100',
    address: '123 Test St, Durham NC',
    years: '1994-2001',
    attending: 'Yes',
    role: 'Setup crew, Magic Circle sound',
    partyMembers: 'Sam Palenchar (spouse) [sam@example.com] | Iris Palenchar (kid)',
    totalInParty: '3',
    pizzaGF: 1, pizzaVegan: 0, pizzaGFVegan: 0,
    notesPrivate: 'We can arrive early to help set up.',
    notesPublic: 'So happy this is happening!',
    listPermission: 'Yes'
  };
  sendEmail_(data);
}

// ============================================================================
//  TESTS
// ============================================================================

// ---- Test config -----------------------------------------------------------

var TEST_SHEET_NAME = 'RSVP_TEST';

// RSVP_HEADERS (the production header row the tests build their sheet from) now
// lives in the Config section at the top, since ensureHeaders_ uses it too.

// ---- Tiny assert + sheet helpers -------------------------------------------

function assertEquals_(label, expected, actual) {
  // String() so 0 and "0", or '' and a blank cell, compare equal.
  if (String(expected) !== String(actual)) {
    throw new Error('FAIL ' + label + ': expected "' + expected + '" but got "' + actual + '"');
  }
  Logger.log('  PASS ' + label);
}

function assertTruthy_(label, actual) {
  if (!actual) throw new Error('FAIL ' + label + ': expected a value but got "' + actual + '"');
  Logger.log('  PASS ' + label);
}

// Build a fresh test sheet with the given headers (defaults to production order).
function makeTestSheet_(headers) {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var existing = ss.getSheetByName(TEST_SHEET_NAME);
  if (existing) ss.deleteSheet(existing);
  var sheet = ss.insertSheet(TEST_SHEET_NAME);
  sheet.appendRow(headers || RSVP_HEADERS);
  return sheet;
}

// Read the most recently appended row back as a {header: value} object.
function lastRowAsObject_(sheet) {
  var values = sheet.getDataRange().getValues();
  var headers = values[0];
  var last = values[values.length - 1];
  var obj = {};
  headers.forEach(function (h, i) { obj[String(h).trim()] = last[i]; });
  return obj;
}

function cleanupTestSheet_() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName(TEST_SHEET_NAME);
  if (sheet) ss.deleteSheet(sheet);
}

// ---- Sample payloads --------------------------------------------------------

function fullPayload_() {
  return {
    firstName: 'Ada', lastName: 'Lovelace', email: 'chloe.palenchar@gmail.com',
    phone: '919-555-0100', address: '1 Analytical Way, Durham NC',
    years: '1994-2001', attending: 'Yes', role: 'Parent, Teacher / Staff',
    partyMembers: 'Sam (spouse) [sam@example.com] | Iris (kid)',
    totalInParty: 3, listPermission: 'Yes',
    notesPrivate: 'Arriving early to help.', notesPublic: 'So excited!',
    pizzaGF: 2, pizzaVegan: 1, pizzaGFVegan: 0
  };
}

// ---- Data-path tests --------------------------------------------------------

function testFullPayload_() {
  Logger.log('testFullPayload_');
  var sheet = makeTestSheet_();
  var data = fullPayload_();

  appendByHeader_(sheet, rsvpRow_(data));
  var row = lastRowAsObject_(sheet);

  assertEquals_('First Name', 'Ada', row['First Name']);
  assertEquals_('Last Name', 'Lovelace', row['Last Name']);
  assertEquals_('Email', 'chloe.palenchar@gmail.com', row['Email']);
  assertEquals_('Phone', '919-555-0100', row['Phone']);
  assertEquals_('Mailing Address', '1 Analytical Way, Durham NC', row['Mailing Address']);
  assertEquals_('Years at Children First', '1994-2001', row['Years at Children First']);
  assertEquals_('Attending', 'Yes', row['Attending']);
  assertEquals_('Role / Affiliation', 'Parent, Teacher / Staff', row['Role / Affiliation']);
  assertEquals_('Party Members', 'Sam (spouse) [sam@example.com] | Iris (kid)', row['Party Members']);
  assertEquals_('Total in Party', 3, row['Total in Party']);
  assertEquals_('List Permission', 'Yes', row['List Permission']);
  assertEquals_('Private Notes', 'Arriving early to help.', row['Private Notes']);
  assertEquals_('Public Notes', 'So excited!', row['Public Notes']);
  assertEquals_('Pizza GF', 2, row['Pizza GF']);
  assertEquals_('Pizza Vegan', 1, row['Pizza Vegan']);
  assertEquals_('Pizza GF+Vegan', 0, row['Pizza GF+Vegan']);
}

function testMissingOptionalFields_() {
  Logger.log('testMissingOptionalFields_');
  var sheet = makeTestSheet_();
  // Only the required fields; everything optional omitted.
  var data = {
    firstName: 'Grace', lastName: 'Hopper', email: 'grace@example.com',
    years: '1985', totalInParty: 1, listPermission: 'No'
  };

  appendByHeader_(sheet, rsvpRow_(data));
  var row = lastRowAsObject_(sheet);

  assertEquals_('First Name', 'Grace', row['First Name']);
  assertEquals_('Attending defaults Yes', 'Yes', row['Attending']);
  assertEquals_('Phone blank', '', row['Phone']);
  assertEquals_('Mailing Address blank', '', row['Mailing Address']);
  assertEquals_('Party Members blank', '', row['Party Members']);
  assertEquals_('Private Notes blank', '', row['Private Notes']);
  assertEquals_('Public Notes blank', '', row['Public Notes']);
  // Pizza counts default to 0 via `data.pizzaGF || 0`, even when absent.
  assertEquals_('Pizza GF defaults 0', 0, row['Pizza GF']);
  assertEquals_('Pizza Vegan defaults 0', 0, row['Pizza Vegan']);
  assertEquals_('Pizza GF+Vegan defaults 0', 0, row['Pizza GF+Vegan']);
}

function testColumnOrderIndependent_() {
  Logger.log('testColumnOrderIndependent_');
  // Same headers, deliberately scrambled order.
  var scrambled = RSVP_HEADERS.slice().reverse();
  var sheet = makeTestSheet_(scrambled);
  var data = fullPayload_();

  appendByHeader_(sheet, rsvpRow_(data));
  var row = lastRowAsObject_(sheet);

  // Values must still land under the right header names despite the reordering.
  assertEquals_('First Name (scrambled)', 'Ada', row['First Name']);
  assertEquals_('Pizza GF (scrambled)', 2, row['Pizza GF']);
  assertEquals_('List Permission (scrambled)', 'Yes', row['List Permission']);
  assertEquals_('Public Notes (scrambled)', 'So excited!', row['Public Notes']);
}

function testUnknownHeaderAndExtraKey_() {
  Logger.log('testUnknownHeaderAndExtraKey_');
  // Sheet has an extra column not in the map; map has an extra key not in the sheet.
  var sheet = makeTestSheet_(RSVP_HEADERS.concat(['Mystery Column']));

  var values = rsvpRow_(fullPayload_());
  values['Ghost Field'] = 'should be ignored';   // key with no matching header

  appendByHeader_(sheet, values);                 // must not throw
  var row = lastRowAsObject_(sheet);

  assertEquals_('Known field still lands', 'Ada', row['First Name']);
  assertEquals_('Unknown header left blank', '', row['Mystery Column']);
  Logger.log('  PASS no crash on extra key/header');
}

function testSpecialCharacters_() {
  Logger.log('testSpecialCharacters_');
  var sheet = makeTestSheet_();
  var data = fullPayload_();
  data.firstName = "O'Brien";
  data.notesPublic = 'Comma, "quote", and <tag> survive';

  appendByHeader_(sheet, rsvpRow_(data));
  var row = lastRowAsObject_(sheet);

  assertEquals_('Apostrophe verbatim', "O'Brien", row['First Name']);
  assertEquals_('Punctuation verbatim', 'Comma, "quote", and <tag> survive', row['Public Notes']);
}

// ---- doPost / edit-token / doGet tests -------------------------------------

function testDoPost_endToEnd_() {
  Logger.log('testDoPost_endToEnd_');
  var sheet = makeTestSheet_();

  // Point doPost at the test sheet for the duration of this test.
  var savedName = RSVP_SHEET_NAME;
  RSVP_SHEET_NAME = TEST_SHEET_NAME;
  try {
    var data = fullPayload_();
    var e = { postData: { contents: JSON.stringify(data) } };

    var res = doPost(e);
    var out = JSON.parse(res.getContent());
    assertEquals_('doPost returns success', 'success', out.status);

    var row = lastRowAsObject_(sheet);
    assertTruthy_('doPost stamped Timestamp', row['Timestamp']);
    assertTruthy_('doPost generated Edit Token', row['Edit Token']);
    assertEquals_('doPost wrote First Name', 'Ada', row['First Name']);
    assertEquals_('doPost wrote Pizza GF', 2, row['Pizza GF']);
    assertEquals_('doPost wrote List Permission', 'Yes', row['List Permission']);
  } finally {
    RSVP_SHEET_NAME = savedName;
  }
}

function testSaveRsvp_updateByToken_() {
  Logger.log('testSaveRsvp_updateByToken_');
  var sheet = makeTestSheet_();

  // First save creates a row + token (no email — saveRsvp_ is the write path only).
  var first = saveRsvp_(sheet, fullPayload_());
  assertTruthy_('token generated on new', first.token);
  assertEquals_('new save is not an update', false, first.isUpdate);

  // Save again with the token and a changed field.
  var upd = fullPayload_();
  upd.firstName = 'Augusta';
  upd.editToken = first.token;
  var second = saveRsvp_(sheet, upd);

  assertEquals_('update reuses token', first.token, second.token);
  assertEquals_('flagged as update', true, second.isUpdate);
  // Row updated in place, not appended (header + 1 data row = 2).
  assertEquals_('row count unchanged after update', 2, sheet.getLastRow());
  var row = lastRowAsObject_(sheet);
  assertEquals_('first name updated', 'Augusta', row['First Name']);
  assertEquals_('token preserved', first.token, row['Edit Token']);
  assertTruthy_('Last Updated stamped', row['Last Updated']);
}

function testGetRsvpForEdit_() {
  Logger.log('testGetRsvpForEdit_');
  var sheet = makeTestSheet_();
  var saved = saveRsvp_(sheet, fullPayload_());   // seed without sending email
  var savedName = RSVP_SHEET_NAME;
  RSVP_SHEET_NAME = TEST_SHEET_NAME;
  try {
    var out = JSON.parse(getRsvpForEdit_(saved.token).getContent());
    assertEquals_('found', true, out.found);
    assertEquals_('record first name', 'Ada', out.record.firstName);
    assertEquals_('record attending defaults Yes', 'Yes', out.record.attending);
    assertEquals_('party parsed count', 2, out.record.party.length);
    assertEquals_('party member name', 'Sam', out.record.party[0].name);
    assertEquals_('party member rel', 'spouse', out.record.party[0].rel);
    assertEquals_('party member email', 'sam@example.com', out.record.party[0].email);

    var miss = JSON.parse(getRsvpForEdit_('no-such-token').getContent());
    assertEquals_('unknown token not found', false, miss.found);
  } finally {
    RSVP_SHEET_NAME = savedName;
  }
}

function testDoGet_excludesRegrets_() {
  Logger.log('testDoGet_excludesRegrets_');
  var sheet = makeTestSheet_();
  var coming = fullPayload_(); coming.firstName = 'Coming'; coming.attending = 'Yes'; coming.partyMembers = '';
  var regret = fullPayload_(); regret.firstName = 'Regret'; regret.attending = 'No';  regret.partyMembers = '';
  saveRsvp_(sheet, coming);   // seed without sending email
  saveRsvp_(sheet, regret);
  var savedName = RSVP_SHEET_NAME;
  RSVP_SHEET_NAME = TEST_SHEET_NAME;
  try {
    var out = JSON.parse(doGet({}).getContent());
    var names = out.grouped.map(function (g) { return g.name; });
    assertTruthy_('attendee listed', names.indexOf('Coming Lovelace') > -1);
    assertEquals_('regret excluded', -1, names.indexOf('Regret Lovelace'));
  } finally {
    RSVP_SHEET_NAME = savedName;
  }
}

function testEnsureHeadersBackfill_() {
  Logger.log('testEnsureHeadersBackfill_');
  // Simulate an older sheet that predates the edit-link columns.
  var oldHeaders = RSVP_HEADERS.filter(function (h) {
    return h !== 'Edit Token' && h !== 'Last Updated';
  });
  var sheet = makeTestSheet_(oldHeaders);

  ensureHeaders_(sheet);
  var headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0]
    .map(function (h) { return String(h).trim(); });

  assertTruthy_('Edit Token backfilled', headers.indexOf('Edit Token') > -1);
  assertTruthy_('Last Updated backfilled', headers.indexOf('Last Updated') > -1);
  // Existing columns are untouched.
  assertEquals_('First Name still col 2', 'First Name', headers[1]);
}

function testEnsureHeadersWideRow_() {
  Logger.log('testEnsureHeadersWideRow_');
  // Older sheet (no edit-link columns) with a data row wider than the header row.
  var oldHeaders = RSVP_HEADERS.filter(function (h) {
    return h !== 'Edit Token' && h !== 'Last Updated';
  });
  var sheet = makeTestSheet_(oldHeaders);
  sheet.getRange(2, oldHeaders.length + 3).setValue('stray');  // value 2 cols past the headers

  ensureHeaders_(sheet);
  var headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0]
    .map(function (h) { return String(h).trim(); });

  // New headers land immediately after the real ones, not after the stray gap.
  assertEquals_('Edit Token right after last header', 'Edit Token', headers[oldHeaders.length]);
  assertEquals_('Last Updated next', 'Last Updated', headers[oldHeaders.length + 1]);
}

function testPickSiteBase_() {
  Logger.log('testPickSiteBase_');
  // Allowlisted hosts: the client URL is returned unchanged.
  assertEquals_('localhost allowed', 'http://localhost:8000/x', pickSiteBase_('http://localhost:8000/x'));
  assertEquals_('prod allowed', 'https://spiralpalooza.org/', pickSiteBase_('https://spiralpalooza.org/'));
  assertEquals_('prod subdomain allowed', 'https://www.spiralpalooza.org/', pickSiteBase_('https://www.spiralpalooza.org/'));
  assertEquals_('pages.dev allowed', 'https://spiralpalooza.pages.dev/', pickSiteBase_('https://spiralpalooza.pages.dev/'));
  // Everything else falls back to SITE_URL (open-redirect / phishing guard).
  assertEquals_('evil w/ localhost query rejected', SITE_URL, pickSiteBase_('https://evil.com/?x=localhost'));
  assertEquals_('localhost subdomain spoof rejected', SITE_URL, pickSiteBase_('https://localhost.attacker.com/'));
  assertEquals_('prod substring spoof rejected', SITE_URL, pickSiteBase_('https://spiralpalooza.org.evil.com/'));
  assertEquals_('non-http rejected', SITE_URL, pickSiteBase_('ftp://spiralpalooza.org/'));
  assertEquals_('empty falls back', SITE_URL, pickSiteBase_(''));
}

function testValidateRsvp_() {
  Logger.log('testValidateRsvp_');
  assertEquals_('valid payload passes', '', validateRsvp_(fullPayload_()));

  var noFirst = fullPayload_(); delete noFirst.firstName;
  assertTruthy_('missing first name rejected', validateRsvp_(noFirst));

  var blankLast = fullPayload_(); blankLast.lastName = '   ';
  assertTruthy_('blank last name rejected', validateRsvp_(blankLast));

  var badEmail = fullPayload_(); badEmail.email = 'not-an-email';
  assertTruthy_('email without @ rejected', validateRsvp_(badEmail));

  var noEmail = fullPayload_(); noEmail.email = '';
  assertTruthy_('missing email rejected', validateRsvp_(noEmail));

  var noYears = fullPayload_(); delete noYears.years;
  assertTruthy_('missing years rejected', validateRsvp_(noYears));

  assertTruthy_('null data rejected', validateRsvp_(null));
}

function testDoPost_rejectsInvalid_() {
  Logger.log('testDoPost_rejectsInvalid_');
  var sheet = makeTestSheet_();
  var savedName = RSVP_SHEET_NAME;
  RSVP_SHEET_NAME = TEST_SHEET_NAME;
  try {
    var bad = fullPayload_(); bad.email = 'nope';   // invalid email -> should be rejected
    var res = doPost({ postData: { contents: JSON.stringify(bad) } });
    var out = JSON.parse(res.getContent());

    assertEquals_('doPost reports error', 'error', out.status);
    assertEquals_('no row written on invalid', 1, sheet.getLastRow());  // header row only
  } finally {
    RSVP_SHEET_NAME = savedName;
  }
}

function testParseParty_() {
  Logger.log('testParseParty_');
  assertEquals_('empty string -> no members', 0, parseParty_('').length);

  var full = parseParty_('Sam (spouse) [sam@example.com]');
  assertEquals_('full member name', 'Sam', full[0].name);
  assertEquals_('full member rel', 'spouse', full[0].rel);
  assertEquals_('full member email', 'sam@example.com', full[0].email);

  var nameOnly = parseParty_('Iris');
  assertEquals_('name-only name', 'Iris', nameOnly[0].name);
  assertEquals_('name-only rel blank', '', nameOnly[0].rel);
  assertEquals_('name-only email blank', '', nameOnly[0].email);

  var relNoEmail = parseParty_('Pat (kid)');
  assertEquals_('rel-no-email rel', 'kid', relNoEmail[0].rel);
  assertEquals_('rel-no-email email blank', '', relNoEmail[0].email);

  var two = parseParty_('Sam (spouse) [sam@x.com] | Iris (kid)');
  assertEquals_('two members parsed', 2, two.length);
  assertEquals_('second member name', 'Iris', two[1].name);
}

function testDoGet_stripsPartyDetails_() {
  Logger.log('testDoGet_stripsPartyDetails_');
  var sheet = makeTestSheet_();
  var p = fullPayload_();
  p.firstName = 'Host'; p.attending = 'Yes'; p.listPermission = 'Yes';
  p.partyMembers = 'Sam (spouse) [sam@example.com] | Iris (kid)';
  saveRsvp_(sheet, p);   // seed without sending email
  var savedName = RSVP_SHEET_NAME;
  RSVP_SHEET_NAME = TEST_SHEET_NAME;
  try {
    var out = JSON.parse(doGet({}).getContent());
    var host = out.grouped.filter(function (g) { return g.name === 'Host Lovelace'; })[0];
    assertTruthy_('host present', host);
    assertEquals_('party count', 2, host.party.length);
    // Public list shows names only — relationship and email are stripped.
    assertEquals_('first party name only', 'Sam', host.party[0]);
    assertEquals_('second party name only', 'Iris', host.party[1]);
    assertEquals_('no email leaks into public output', -1, JSON.stringify(out).indexOf('sam@example.com'));
  } finally {
    RSVP_SHEET_NAME = savedName;
  }
}

// ---- Runner (this is the one to pick in the Run dropdown) -------------------

function runAllRsvpTests() {
  testFullPayload_();
  testMissingOptionalFields_();
  testColumnOrderIndependent_();
  testUnknownHeaderAndExtraKey_();
  testSpecialCharacters_();
  testEnsureHeadersBackfill_();
  testEnsureHeadersWideRow_();
  testValidateRsvp_();
  testParseParty_();
  testDoPost_endToEnd_();
  testSaveRsvp_updateByToken_();
  testGetRsvpForEdit_();
  testDoPost_rejectsInvalid_();
  testDoGet_excludesRegrets_();
  testDoGet_stripsPartyDetails_();
  cleanupTestSheet_();
  Logger.log('ALL RSVP DATA-PATH TESTS PASSED');
}

// ---- email html assert helpers ---------------------------------------------

function assertHas_(label, html, needle) {
  if (html.indexOf(needle) === -1) {
    throw new Error('FAIL ' + label + ': expected HTML to contain "' + needle + '"');
  }
  Logger.log('  PASS ' + label);
}

function assertLacks_(label, html, needle) {
  if (html.indexOf(needle) !== -1) {
    throw new Error('FAIL ' + label + ': expected HTML to NOT contain "' + needle + '"');
  }
  Logger.log('  PASS ' + label);
}

// ---- email html tests ------------------------------------------------------

function testEmail_fullPayload_() {
  Logger.log('testEmail_fullPayload_');
  var html = genEmailHTML_({
    firstName: 'Ada', lastName: 'Lovelace', years: '1994-2001',
    role: 'Parent', partyMembers: 'Sam (spouse) | Iris (kid)',
    pizzaGF: 2, pizzaVegan: 1, pizzaGFVegan: 0,
    notesPublic: 'So excited!', notesPrivate: 'Arriving early.'
  });

  assertHas_('name', html, 'Ada Lovelace');
  assertHas_('years', html, '1994-2001');
  assertHas_('role', html, 'CF Affiliation:</strong> Parent');
  assertHas_('party member Sam', html, '<li>Sam (spouse)</li>');
  assertHas_('party member Iris', html, '<li>Iris (kid)</li>');
  assertHas_('pizza gf', html, '2 gluten-free');
  assertHas_('pizza vegan', html, '1 vegan');
  assertLacks_('no gf+vegan (was 0)', html, 'gluten-free + vegan');
  assertHas_('public note', html, 'So excited!');
  assertHas_('private note', html, 'Arriving early.');
}

function testEmail_minimalPayload_() {
  Logger.log('testEmail_minimalPayload_');
  // Only required-ish fields; no party, no pizza, no role, no notes.
  var html = genEmailHTML_({ firstName: 'Grace', lastName: 'Hopper', years: '1985' });

  assertHas_('name', html, 'Grace Hopper');
  assertHas_('empty party fallback', html, '(just you, for now)');
  assertLacks_('no role line', html, 'CF Affiliation');
  assertLacks_('no pizza block', html, 'Special-order pizza');
  assertLacks_('no public note', html, 'Your public note');
  assertLacks_('no private note', html, 'Your private note');
}

function testEmail_escapesHtml_() {
  Logger.log('testEmail_escapesHtml_');
  var html = genEmailHTML_({
    firstName: '<script>', lastName: 'O\'Brien', years: '2000',
    notesPublic: 'a & b <tag>'
  });

  // User input must be escaped, not rendered as live markup.
  assertHas_('escaped name', html, '&lt;script&gt;');
  assertLacks_('no raw script tag', html, '<script>');
  assertHas_('escaped ampersand', html, 'a &amp; b &lt;tag&gt;');
}

function testEmail_regretAndEditLink_() {
  Logger.log('testEmail_regretAndEditLink_');
  // Regret email: no party/pizza details, but the edit link is present.
  var regret = genEmailHTML_(
    { firstName: 'Grace', attending: 'No', notesPublic: 'Wish I could come!' },
    'https://example.org/?edit=tok123&type=rsvp',
    false
  );
  assertHas_('regret greeting', regret, "can't make it");
  assertHas_('regret message', regret, 'Wish I could come!');
  assertHas_('edit link present', regret, 'edit=tok123');
  assertLacks_('no pizza in regret', regret, 'Special-order pizza');

  // Attending (happy-path) email also carries the edit link.
  var attending = genEmailHTML_(
    { firstName: 'Ada', attending: 'Yes', years: '1994' },
    'https://example.org/?edit=tok999&type=rsvp',
    false
  );
  assertHas_('edit link in attending email', attending, 'edit=tok999');

  // Update email uses the "updated" heading.
  var updated = genEmailHTML_({ firstName: 'Ada', attending: 'Yes', years: '1994' }, '', true);
  assertHas_('updated heading', updated, 'Your RSVP has been updated');
}

// ---- runner (pick this in the Run dropdown) ---------------------------------

function runEmailTests() {
  testEmail_fullPayload_();
  testEmail_minimalPayload_();
  testEmail_escapesHtml_();
  testEmail_regretAndEditLink_();
  testPickSiteBase_();
  Logger.log('ALL EMAIL HTML TESTS PASSED');
}
