/**
 * ============================================================================
 *  WARNING — THIS FILE IS SOURCE-CONTROLLED (spiralpalooza git repo)
 *
 *  DO NOT EDIT this file until you have read the "Working on the Apps Script
 *  backends with clasp" section of the repo's README.md. Editing the live
 *  version directly can drift from, or be overwritten by, the git copy.
 * ============================================================================
 *
 * Spiralpalooza T-shirt orders — Apps Script backend (container-bound to the
 * Shirt Orders sheet).
 *
 * Endpoints:
 *   doPost  — append a new order, or update an existing one by edit token
 *   doGet   — ?edit=<token> returns one order for the edit form;
 *             otherwise returns a simple status (there is no public shirt list)
 *
 * Sheet headers (row 1, any order — reads/writes are header-keyed):
 *   Timestamp | Name | Email | <20 size columns> | Notes | Edit Token | Last Updated
 *
 * Script Properties (Project Settings -> Script Properties):
 *   MAILER_URL   — /exec URL of the shared mailer microservice
 *   MAIL_SECRET  — shared secret the mailer checks (same value as the mailer)
 */

// ---- Config ----------------------------------------------------------------

var SHIRT_SHEET_NAME = 'Shirt Orders';

// Live site base URL, must end with '/'. Used to build the edit link in emails.
var SITE_URL = 'https://spiralpalooza.org/';

// The orderable sizes, in display order. Each is also a sheet column header, and
// the keys the frontend sends in its `sizes` object must match these exactly.
var SHIRT_SIZES = [
  'Adult XS', 'Adult Small', 'Adult Medium',
  'Adult Large', 'Adult XL', 'Adult 2XL', 'Adult 3XL',
  'Femme XS', 'Femme Small', 'Femme Medium',
  'Femme Large', 'Femme XL', 'Femme 2XL',
  'Youth 2T', 'Youth 3T', 'Youth 4T',
  'Youth Small (6-8)', 'Youth Medium (10-12)',
  'Youth Large (14-16)', 'Youth XL'
];

// Full header row, in canonical order. ensureHeaders_ uses this to create the
// sheet or to backfill any missing columns (e.g. Edit Token on an older sheet).
var SHIRT_HEADERS = ['Timestamp', 'Name', 'Email']
  .concat(SHIRT_SIZES)
  .concat(['Notes', 'Edit Token', 'Last Updated']);

// ---- Write path (doPost) ---------------------------------------------------

function doPost(e) {
  try {
    var data = parsePayload_(e);

    // Reject incomplete submissions before touching the sheet or sending mail.
    // This is data-integrity validation, NOT access control — the endpoint is public.
    var problem = validateOrder_(data);
    if (problem) {
      return ContentService
        .createTextOutput(JSON.stringify({ status: "error", message: problem }))
        .setMimeType(ContentService.MimeType.JSON);
    }

    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = ss.getSheetByName(SHIRT_SHEET_NAME) || ss.insertSheet(SHIRT_SHEET_NAME);
    ensureHeaders_(sheet);

    var saved = saveOrder_(sheet, data);

    sendEmail_(data, saved.token, saved.isUpdate);

    return ContentService
      .createTextOutput(JSON.stringify({ status: "success" }))
      .setMimeType(ContentService.MimeType.JSON);

  } catch (err) {
    console.error('doPost failed: ' + (err && err.stack ? err.stack : err));
    return ContentService
      .createTextOutput(JSON.stringify({ status: "error", message: err.toString() }))
      .setMimeType(ContentService.MimeType.JSON);
  }
}

// Accepts either a JSON body or a form POST with a `payload` field, so the
// endpoint keeps working if the frontend ever switches off no-cors JSON.
function parsePayload_(e) {
  if (e && e.postData && e.postData.type === "application/json") {
    return JSON.parse(e.postData.contents);
  }
  if (e && e.parameter && e.parameter.payload) {
    return JSON.parse(e.parameter.payload);
  }
  if (e && e.postData && e.postData.contents) {
    return JSON.parse(e.postData.contents);
  }
  return (e && e.parameter) || {};
}

// Maps an incoming order payload to sheet columns by header text. Timestamp,
// Edit Token, and Last Updated are managed by doPost / updateRowByToken_.
function shirtRow_(data) {
  var sizes = data.sizes || {};
  var values = {
    'Name':  data.name,
    'Email': data.email,
    'Notes': data.notes
  };
  SHIRT_SIZES.forEach(function (size) {
    values[size] = parseInt(sizes[size], 10) || 0;
  });
  return values;
}

// Writes the order to the sheet: updates the row matching data.editToken if found,
// otherwise appends a new row with a fresh token. Returns { token, isUpdate }.
// No email/validation here — kept separate from doPost so the write path can be
// tested without going through the email code path.
function saveOrder_(sheet, data) {
  var values = shirtRow_(data);

  if (data.editToken) {
    values['Last Updated'] = new Date();
    if (updateRowByToken_(sheet, data.editToken, values)) {
      return { token: data.editToken, isUpdate: true };
    }
  }
  var token = Utilities.getUuid();      // new order, or editToken not found (falls back to new)
  values['Timestamp'] = new Date();
  values['Edit Token'] = token;
  appendByHeader_(sheet, values);
  return { token: token, isUpdate: false };
}

// Validates the genuinely required fields for data integrity (NOT access control
// — the endpoint is public; this just keeps junk/incomplete rows out). Returns an
// error message string, or '' if the payload is acceptable.
function validateOrder_(data) {
  if (!data) return 'Missing request body.';
  if (!String(data.name || '').trim()) return 'Name is required.';
  var email = String(data.email || '').trim();
  if (!email || email.indexOf('@') === -1) return 'A valid email is required.';
  if (totalShirts_(data.sizes) < 1) return 'Order at least one shirt.';
  return '';
}

// Sum of all size quantities in a sizes object (size -> qty).
function totalShirts_(sizes) {
  sizes = sizes || {};
  return SHIRT_SIZES.reduce(function (sum, size) {
    return sum + (parseInt(sizes[size], 10) || 0);
  }, 0);
}

// Create the sheet's header row if it's empty, or backfill any missing headers
// (Edit Token / Last Updated may not exist on an order sheet from before the
// edit-link feature). Existing columns and their order are left untouched.
function ensureHeaders_(sheet) {
  if (sheet.getLastRow() === 0) {
    sheet.appendRow(SHIRT_HEADERS);
    sheet.getRange(1, 1, 1, SHIRT_HEADERS.length).setFontWeight('bold');
    sheet.setFrozenRows(1);
    return;
  }
  var headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0]
    .map(function (h) { return String(h).trim(); });
  var missing = SHIRT_HEADERS.filter(function (h) { return headers.indexOf(h) === -1; });
  if (missing.length) {
    var start = headers.length + 1;
    sheet.getRange(1, start, 1, missing.length).setValues([missing]).setFontWeight('bold');
  }
}

// Append a row by matching the values object's keys to the sheet's header row.
// Column order in the sheet does not have to match code order: a header with no
// matching key is left blank, and a key with no matching header is ignored.
function appendByHeader_(sheet, values) {
  var headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
  var row = headers.map(function (h) {
    var key = String(h).trim();
    return Object.prototype.hasOwnProperty.call(values, key) ? values[key] : '';
  });
  sheet.appendRow(row);
}

// Finds the row whose 'Edit Token' matches and overwrites it. Columns not present
// in `values` (Timestamp, Edit Token) keep their existing cell. Returns false if
// no row matches, so doPost can fall back to appending a new row.
function updateRowByToken_(sheet, token, values) {
  var grid = sheet.getDataRange().getValues();
  var headers = grid[0];
  var tokenCol = headers.indexOf('Edit Token');
  if (tokenCol === -1) return false;

  for (var i = 1; i < grid.length; i++) {
    if (String(grid[i][tokenCol]) === String(token)) {
      var row = headers.map(function (h, c) {
        var key = String(h).trim();
        return Object.prototype.hasOwnProperty.call(values, key) ? values[key] : grid[i][c];
      });
      sheet.getRange(i + 1, 1, 1, row.length).setValues([row]);
      return true;
    }
  }
  return false;
}

// ---- Read path (doGet) -----------------------------------------------------

function doGet(e) {
  if (e && e.parameter && e.parameter.edit) {
    return getOrderForEdit_(e.parameter.edit);
  }
  // No public shirt list — the only GET use is the edit-mode prefetch above.
  return ContentService
    .createTextOutput(JSON.stringify({ status: "success" }))
    .setMimeType(ContentService.MimeType.JSON);
}

// Returns one order by edit token, shaped for the edit form: {found, record}.
function getOrderForEdit_(token) {
  try {
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(SHIRT_SHEET_NAME);
    var grid = sheet.getDataRange().getValues();
    var headers = grid[0];
    var col = {};
    headers.forEach(function (h, i) { col[String(h).trim()] = i; });
    var tokenCol = col['Edit Token'];

    var result = { found: false };
    if (tokenCol != null) {
      for (var i = 1; i < grid.length; i++) {
        if (String(grid[i][tokenCol]) === String(token)) {
          var r = grid[i];
          var get = function (name) { return col[name] != null ? r[col[name]] : ''; };
          var sizes = {};
          SHIRT_SIZES.forEach(function (size) {
            sizes[size] = parseInt(get(size), 10) || 0;
          });
          result = {
            found: true,
            record: {
              name:  get('Name'),
              email: get('Email'),
              sizes: sizes,
              notes: get('Notes')
            }
          };
          break;
        }
      }
    }
    return ContentService
      .createTextOutput(JSON.stringify(result))
      .setMimeType(ContentService.MimeType.JSON);

  } catch (err) {
    console.error('getOrderForEdit_ failed: ' + err);
    return ContentService
      .createTextOutput(JSON.stringify({ found: false, error: err.toString() }))
      .setMimeType(ContentService.MimeType.JSON);
  }
}

// ---- Email -----------------------------------------------------------------

// Build and send the order confirmation. Best-effort: sendConfirmation_ swallows
// failures, and we bail early if there's no usable email address.
function sendEmail_(data, token, isUpdate) {
  if (!data.email || data.email.indexOf('@') === -1) return;
  var base = pickSiteBase_(data.siteUrl);
  var sep = base.indexOf('?') === -1 ? '?' : '&';
  var editUrl = token ? (base + sep + 'edit=' + token + '&type=shirt') : '';
  sendConfirmation_(data.email, 'Your Spiralpalooza t-shirt order', genEmailHTML_(data, editUrl, isUpdate));
}

// Builds the edit-link base from the URL the form was served from (data.siteUrl),
// so links work across local/preview/production without code changes. The caller's
// URL is only trusted if its host is on the allowlist — otherwise we fall back to
// the configured SITE_URL, to avoid becoming a phishing/open-redirect vector (the
// link lands in an email, so an attacker-controlled URL could not be allowed through).
function pickSiteBase_(clientUrl) {
  if (clientUrl && /^https?:\/\//i.test(clientUrl)) {
    // Match on the URL's HOST, not a substring — a substring check would also let
    // "https://evil.com/?x=localhost" or "https://localhost.attacker.com/" through.
    var m = clientUrl.match(/^https?:\/\/([^\/?#]+)/i);
    var host = m ? m[1].split(':')[0].toLowerCase() : '';
    if (host === 'localhost' || host === '127.0.0.1' ||
        host === 'spiralpalooza.org' || host.endsWith('.spiralpalooza.org') ||
        host === 'spiralpalooza.pages.dev' || host.endsWith('.spiralpalooza.pages.dev')) {
      return clientUrl;
    }
  }
  return SITE_URL;
}

// Generate the email HTML. Factored out to make this testable without sending email.
function genEmailHTML_(data, editUrl, isUpdate) {
  var heading = isUpdate ? 'Your t-shirt order has been updated' : 'We got your t-shirt order!';
  var editLine = editUrl
    ? '<p style="color:#7A4010;font-size:13px">Need to change your order? Use your personal link to update it:<br><a href="' + editUrl + '">' + editUrl + '</a></p>'
    : '';

  var sizes = data.sizes || {};
  var lines = [];
  var total = 0;
  SHIRT_SIZES.forEach(function (size) {
    var qty = parseInt(sizes[size], 10) || 0;
    if (qty > 0) {
      lines.push('<li>' + esc_(size) + ': <strong>' + qty + '</strong></li>');
      total += qty;
    }
  });

  return [
    '<div style="font-family:Arial,sans-serif;color:#3D1C00;line-height:1.6">',
      '<h2 style="color:#7B3A0E">' + heading + '</h2>',
      '<p>Hi ' + esc_(data.name) + ',</p>',
      '<p>Thanks for ordering your Spiralpalooza commemorative shirt, ' +
        'designed by Durham illustrator Iris Gottlieb.</p>',
      '<p><strong>Your order (' + total + ' shirt' + (total === 1 ? '' : 's') + '):</strong></p>',
      '<ul>', lines.join(''), '</ul>',
      (data.notes ? '<p><strong>Your notes:</strong> ' + esc_(data.notes) + '</p>' : ''),
      '<p>We\'ll be in touch about payment soon.</p>',
      editLine,
    '</div>'
  ].join('');
}

// Best-effort confirmation send. Calls the mailer microservice server-to-server
// so the email goes out from childrenfirstmail, not from this script's owner.
// Never throws — a mail hiccup must not fail the order write.
// A copy of this goes in each script.
function sendConfirmation_(to, subject, htmlBody) {
  try {
    var props = PropertiesService.getScriptProperties();
    var url = props.getProperty('MAILER_URL');
    var secret = props.getProperty('MAIL_SECRET');
    if (!url || !secret || !to) return;

    UrlFetchApp.fetch(url, {
      method: 'post',
      contentType: 'application/json',
      muteHttpExceptions: true,
      payload: JSON.stringify({ secret: secret, to: to, subject: subject, htmlBody: htmlBody })
    });
  } catch (err) {
    // swallow — confirmation email is non-critical
  }
}

// Escape user-supplied text before dropping it into HTML.
function esc_(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// ============================================================================
//  TESTS  (run runAllShirtTests / runEmailTests from the editor Run dropdown)
// ============================================================================

var TEST_SHEET_NAME = 'Shirt_TEST';

// ---- Tiny assert + sheet helpers -------------------------------------------

function assertEquals_(label, expected, actual) {
  // String() so 0 and "0", or '' and a blank cell, compare equal.
  if (String(expected) !== String(actual)) {
    throw new Error('FAIL ' + label + ': expected "' + expected + '" but got "' + actual + '"');
  }
  Logger.log('  PASS ' + label);
}

function assertTruthy_(label, actual) {
  if (!actual) throw new Error('FAIL ' + label + ': expected a value but got "' + actual + '"');
  Logger.log('  PASS ' + label);
}

// Build a fresh test sheet with the given headers (defaults to production order).
function makeTestSheet_(headers) {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var existing = ss.getSheetByName(TEST_SHEET_NAME);
  if (existing) ss.deleteSheet(existing);
  var sheet = ss.insertSheet(TEST_SHEET_NAME);
  sheet.appendRow(headers || SHIRT_HEADERS);
  return sheet;
}

// Read the most recently appended row back as a {header: value} object.
function lastRowAsObject_(sheet) {
  var values = sheet.getDataRange().getValues();
  var headers = values[0];
  var last = values[values.length - 1];
  var obj = {};
  headers.forEach(function (h, i) { obj[String(h).trim()] = last[i]; });
  return obj;
}

function cleanupTestSheet_() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName(TEST_SHEET_NAME);
  if (sheet) ss.deleteSheet(sheet);
}

// ---- Sample payloads --------------------------------------------------------

function fullPayload_() {
  return {
    name: 'Ada Lovelace',
    email: 'chloe.palenchar@gmail.com',
    sizes: { 'Adult Medium': 2, 'Femme Small': 1, 'Youth 4T': 0 },
    notes: 'Please bundle these together.'
  };
}

// ---- Data-path tests --------------------------------------------------------

function testFullPayload_() {
  Logger.log('testFullPayload_');
  var sheet = makeTestSheet_();
  appendByHeader_(sheet, shirtRow_(fullPayload_()));
  var row = lastRowAsObject_(sheet);

  assertEquals_('Name', 'Ada Lovelace', row['Name']);
  assertEquals_('Email', 'chloe.palenchar@gmail.com', row['Email']);
  assertEquals_('Adult Medium qty', 2, row['Adult Medium']);
  assertEquals_('Femme Small qty', 1, row['Femme Small']);
  assertEquals_('Unset size defaults 0', 0, row['Adult XS']);
  assertEquals_('Notes', 'Please bundle these together.', row['Notes']);
}

function testMissingOptionalFields_() {
  Logger.log('testMissingOptionalFields_');
  var sheet = makeTestSheet_();
  appendByHeader_(sheet, shirtRow_({ name: 'Grace Hopper', email: 'grace@example.com', sizes: { 'Adult XL': 1 } }));
  var row = lastRowAsObject_(sheet);

  assertEquals_('Name', 'Grace Hopper', row['Name']);
  assertEquals_('Adult XL qty', 1, row['Adult XL']);
  assertEquals_('Notes blank', '', row['Notes']);
  assertEquals_('Other size defaults 0', 0, row['Youth Small (6-8)']);
}

function testColumnOrderIndependent_() {
  Logger.log('testColumnOrderIndependent_');
  var scrambled = SHIRT_HEADERS.slice().reverse();
  var sheet = makeTestSheet_(scrambled);
  appendByHeader_(sheet, shirtRow_(fullPayload_()));
  var row = lastRowAsObject_(sheet);

  assertEquals_('Name (scrambled)', 'Ada Lovelace', row['Name']);
  assertEquals_('Adult Medium (scrambled)', 2, row['Adult Medium']);
  assertEquals_('Notes (scrambled)', 'Please bundle these together.', row['Notes']);
}

function testEnsureHeadersBackfill_() {
  Logger.log('testEnsureHeadersBackfill_');
  // Simulate an older sheet that predates the edit-link columns.
  var oldHeaders = ['Timestamp', 'Name', 'Email'].concat(SHIRT_SIZES).concat(['Notes']);
  var sheet = makeTestSheet_(oldHeaders);

  ensureHeaders_(sheet);
  var headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0]
    .map(function (h) { return String(h).trim(); });

  assertTruthy_('Edit Token backfilled', headers.indexOf('Edit Token') > -1);
  assertTruthy_('Last Updated backfilled', headers.indexOf('Last Updated') > -1);
  // Existing columns are untouched.
  assertEquals_('Name still col 2', 'Name', headers[1]);
}

function testValidateOrder_() {
  Logger.log('testValidateOrder_');
  assertEquals_('valid payload passes', '', validateOrder_(fullPayload_()));

  var noName = fullPayload_(); noName.name = '   ';
  assertTruthy_('blank name rejected', validateOrder_(noName));

  var badEmail = fullPayload_(); badEmail.email = 'nope';
  assertTruthy_('email without @ rejected', validateOrder_(badEmail));

  var noShirts = fullPayload_(); noShirts.sizes = { 'Adult Medium': 0 };
  assertTruthy_('zero-quantity order rejected', validateOrder_(noShirts));

  assertTruthy_('null data rejected', validateOrder_(null));
}

function testDoPost_endToEnd_() {
  Logger.log('testDoPost_endToEnd_');
  var sheet = makeTestSheet_();
  var savedName = SHIRT_SHEET_NAME;
  SHIRT_SHEET_NAME = TEST_SHEET_NAME;
  try {
    var res = doPost({ postData: { type: 'application/json', contents: JSON.stringify(fullPayload_()) } });
    var out = JSON.parse(res.getContent());
    assertEquals_('doPost returns success', 'success', out.status);

    var row = lastRowAsObject_(sheet);
    assertTruthy_('doPost stamped Timestamp', row['Timestamp']);
    assertTruthy_('doPost generated Edit Token', row['Edit Token']);
    assertEquals_('doPost wrote Name', 'Ada Lovelace', row['Name']);
    assertEquals_('doPost wrote Adult Medium', 2, row['Adult Medium']);
  } finally {
    SHIRT_SHEET_NAME = savedName;
  }
}

function testDoPost_rejectsInvalid_() {
  Logger.log('testDoPost_rejectsInvalid_');
  var sheet = makeTestSheet_();
  var savedName = SHIRT_SHEET_NAME;
  SHIRT_SHEET_NAME = TEST_SHEET_NAME;
  try {
    var bad = fullPayload_(); bad.email = 'nope';
    var res = doPost({ postData: { type: 'application/json', contents: JSON.stringify(bad) } });
    var out = JSON.parse(res.getContent());

    assertEquals_('doPost reports error', 'error', out.status);
    assertEquals_('no row written on invalid', 1, sheet.getLastRow());  // header row only
  } finally {
    SHIRT_SHEET_NAME = savedName;
  }
}

function testSaveOrder_updateByToken_() {
  Logger.log('testSaveOrder_updateByToken_');
  var sheet = makeTestSheet_();

  var first = saveOrder_(sheet, fullPayload_());
  assertTruthy_('token generated on new', first.token);
  assertEquals_('new save is not an update', false, first.isUpdate);

  var upd = fullPayload_();
  upd.sizes = { 'Adult Medium': 5 };
  upd.editToken = first.token;
  var second = saveOrder_(sheet, upd);

  assertEquals_('update reuses token', first.token, second.token);
  assertEquals_('flagged as update', true, second.isUpdate);
  assertEquals_('row count unchanged after update', 2, sheet.getLastRow());
  var row = lastRowAsObject_(sheet);
  assertEquals_('quantity updated', 5, row['Adult Medium']);
  assertEquals_('cleared size now 0', 0, row['Femme Small']);
  assertEquals_('token preserved', first.token, row['Edit Token']);
  assertTruthy_('Last Updated stamped', row['Last Updated']);
}

function testGetOrderForEdit_() {
  Logger.log('testGetOrderForEdit_');
  var sheet = makeTestSheet_();
  var saved = saveOrder_(sheet, fullPayload_());
  var savedName = SHIRT_SHEET_NAME;
  SHIRT_SHEET_NAME = TEST_SHEET_NAME;
  try {
    var out = JSON.parse(getOrderForEdit_(saved.token).getContent());
    assertEquals_('found', true, out.found);
    assertEquals_('record name', 'Ada Lovelace', out.record.name);
    assertEquals_('record size qty', 2, out.record.sizes['Adult Medium']);
    assertEquals_('record notes', 'Please bundle these together.', out.record.notes);

    var miss = JSON.parse(getOrderForEdit_('no-such-token').getContent());
    assertEquals_('unknown token not found', false, miss.found);
  } finally {
    SHIRT_SHEET_NAME = savedName;
  }
}

// ---- Runner (this is the one to pick in the Run dropdown) -------------------

function runAllShirtTests() {
  testFullPayload_();
  testMissingOptionalFields_();
  testColumnOrderIndependent_();
  testEnsureHeadersBackfill_();
  testValidateOrder_();
  testDoPost_endToEnd_();
  testDoPost_rejectsInvalid_();
  testSaveOrder_updateByToken_();
  testGetOrderForEdit_();
  cleanupTestSheet_();
  Logger.log('ALL SHIRT DATA-PATH TESTS PASSED');
}

// ---- email html assert helpers ---------------------------------------------

function assertHas_(label, html, needle) {
  if (html.indexOf(needle) === -1) {
    throw new Error('FAIL ' + label + ': expected HTML to contain "' + needle + '"');
  }
  Logger.log('  PASS ' + label);
}

function assertLacks_(label, html, needle) {
  if (html.indexOf(needle) !== -1) {
    throw new Error('FAIL ' + label + ': expected HTML to NOT contain "' + needle + '"');
  }
  Logger.log('  PASS ' + label);
}

// ---- email html tests ------------------------------------------------------

function testEmail_fullPayload_() {
  Logger.log('testEmail_fullPayload_');
  var html = genEmailHTML_({
    name: 'Ada Lovelace',
    sizes: { 'Adult Medium': 2, 'Femme Small': 1 },
    notes: 'Bundle please.'
  }, 'https://example.org/?edit=tok123&type=shirt', false);

  assertHas_('name', html, 'Ada Lovelace');
  assertHas_('size line', html, 'Adult Medium: <strong>2</strong>');
  assertHas_('second size line', html, 'Femme Small: <strong>1</strong>');
  assertHas_('total count', html, '(3 shirts)');
  assertHas_('notes', html, 'Bundle please.');
  assertHas_('edit link present', html, 'edit=tok123');
  assertHas_('new-order heading', html, 'We got your t-shirt order!');
}

function testEmail_singularAndNoNotes_() {
  Logger.log('testEmail_singularAndNoNotes_');
  var html = genEmailHTML_({ name: 'Grace', sizes: { 'Adult XL': 1 } }, '', false);

  assertHas_('singular shirt', html, '(1 shirt)');
  assertLacks_('no notes block', html, 'Your notes:');
  assertLacks_('no edit line when url blank', html, 'personal link');
}

function testEmail_updateHeading_() {
  Logger.log('testEmail_updateHeading_');
  var html = genEmailHTML_({ name: 'Ada', sizes: { 'Adult Medium': 1 } }, 'https://example.org/?edit=tok9&type=shirt', true);
  assertHas_('updated heading', html, 'Your t-shirt order has been updated');
  assertHas_('edit link in update', html, 'edit=tok9');
}

function testEmail_escapesHtml_() {
  Logger.log('testEmail_escapesHtml_');
  var html = genEmailHTML_({ name: '<script>', sizes: { 'Adult Medium': 1 }, notes: 'a & b <tag>' }, '', false);
  assertHas_('escaped name', html, '&lt;script&gt;');
  assertLacks_('no raw script tag', html, '<script>');
  assertHas_('escaped notes', html, 'a &amp; b &lt;tag&gt;');
}

// ---- runner (pick this in the Run dropdown) ---------------------------------

function runEmailTests() {
  testEmail_fullPayload_();
  testEmail_singularAndNoNotes_();
  testEmail_updateHeading_();
  testEmail_escapesHtml_();
  Logger.log('ALL EMAIL HTML TESTS PASSED');
}
